//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaNhaHang
    {
        public int MaDGNH { get; set; }
        public string MoTaDanhGia { get; set; }
        public decimal DiemDG { get; set; }
        public string MaKH { get; set; }
        public string MaNH { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhaHang NhaHang { get; set; }
    }
}
