//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public string MaDon { get; set; }
        public string MaKH { get; set; }
        public string MaNH { get; set; }
        public string MaShipper { get; set; }
        public string TrangThai { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> ThoiGianDat { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> ShipperLatitude { get; set; }
        public Nullable<double> ShipperLongitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhaHang NhaHang { get; set; }
        public virtual Shipper Shipper { get; set; }
    }
}
