//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACN
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.LichSuGioHangs = new HashSet<LichSuGioHang>();
        }
    
        public string MaMon { get; set; }
        public string MaNH { get; set; }
        public string TenMon { get; set; }
        public string MaLoai { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGioHang> LichSuGioHangs { get; set; }
        public virtual LoaiMonAn LoaiMonAn { get; set; }
        public virtual NhaHang NhaHang { get; set; }
    }
}
