//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACN
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaHang()
        {
            this.DanhGiaNhaHangs = new HashSet<DanhGiaNhaHang>();
            this.DonHangs = new HashSet<DonHang>();
            this.LichSuGioHangs = new HashSet<LichSuGioHang>();
            this.MonAns = new HashSet<MonAn>();
        }
    
        public string MaNH { get; set; }
        public string TenNH { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string MaTK { get; set; }
        public string TrangThai { get; set; }
        public string HinhAnh { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaNhaHang> DanhGiaNhaHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGioHang> LichSuGioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonAn> MonAns { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
